---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-QueryLog-WithStackTrace
no_index:
  directory:
    - t
    - inc
requires:
  DBD::SQLite: 0
  DBI: 0
  DBIx::Class: 0
  DBIx::Class::QueryLog: 1.003002
  Devel::StackTrace: 1.21
  File::Temp: 0
  Moose: 0.9
version: 1.0
x_resource:
  repository: https://github.com/DrHyde/perl-modules-DBIx-Class-QueryLog-WithStackTrace
